load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "try_array_in_func",
    srcs = ["array_in_func.cc"],
)

cc_binary(
  name = "init_time",
  srcs = ["init_time.cc"],
)

cc_binary(
  name = "undefine",
  srcs = ["undefine.cc"],
)

cc_binary(
  name = "delete_constructor",
  srcs = ["delete_constructor.cc"],
)

